### ISSUE TITLE
Running Jenkins

### ISSUE THREAD

**Issue by Thihup** [piranhacloud/piranha#743]
Hello!

I will try to run Jenkins 2.236 in both Piranha Micro and Server and report here the issues I'll found.
I think it's a good real example that I can try.

I'll start with Piranha Micro 20.6.0-SNAPSHOT

Just running I get the following exception:
```
Exception in thread "main" java.lang.RuntimeException: Unable to start servicing
	at cloud.piranha.webapp.impl.DefaultWebApplication.verifyState(DefaultWebApplication.java:1946)
	at cloud.piranha.webapp.impl.DefaultWebApplication.start(DefaultWebApplication.java:1841)
	at cloud.piranha.appserver.impl.DefaultWebApplicationServer.lambda$start$1(DefaultWebApplicationServer.java:306)
	at cloud.piranha.appserver.impl.DefaultWebApplicationServer$$Lambda$174/0000000000000000.accept(Unknown Source)
	at java.base/java.util.HashMap$Values.forEach(HashMap.java:1068)
	at cloud.piranha.appserver.impl.DefaultWebApplicationServer.start(DefaultWebApplicationServer.java:302)
	at cloud.piranha.micro.MicroPiranha.run(MicroPiranha.java:215)
	at cloud.piranha.micro.MicroPiranha.main(MicroPiranha.java:204)

```

Enable logging, I get the following:

```
ADVERTÊNCIA: Initializer org.jboss.weld.environment.servlet.EnhancedListener failing onStartup
java.lang.RuntimeException: javax.naming.NamingException: Cannot call any method on a closed context
	at cloud.piranha.cdi.weld.WeldContainer.initialize(WeldContainer.java:74)
	at org.jboss.weld.environment.servlet.WeldServletLifecycle.initialize(WeldServletLifecycle.java:214)
	at org.jboss.weld.environment.servlet.EnhancedListener.onStartup(EnhancedListener.java:62)
	at cloud.piranha.webapp.impl.DefaultWebApplication.initializeInitializers(DefaultWebApplication.java:1314)
	at cloud.piranha.webapp.impl.DefaultWebApplication.initialize(DefaultWebApplication.java:1265)
	at cloud.piranha.appserver.impl.DefaultWebApplicationServer.lambda$initialize$0(DefaultWebApplicationServer.java:203)
	at cloud.piranha.appserver.impl.DefaultWebApplicationServer$$Lambda$13/0000000000000000.accept(Unknown Source)
	at java.base/java.util.HashMap$Values.forEach(HashMap.java:1068)
	at cloud.piranha.appserver.impl.DefaultWebApplicationServer.initialize(DefaultWebApplicationServer.java:199)
	at cloud.piranha.micro.MicroPiranha.run(MicroPiranha.java:214)
	at cloud.piranha.micro.MicroPiranha.main(MicroPiranha.java:204)
Caused by: javax.naming.NamingException: Cannot call any method on a closed context
	at cloud.piranha.jndi.memory.DefaultInitialContext.checkClosed(DefaultInitialContext.java:139)
	at cloud.piranha.jndi.memory.DefaultInitialContext.rebind(DefaultInitialContext.java:463)
	at java.naming/javax.naming.InitialContext.rebind(InitialContext.java:425)
	at cloud.piranha.cdi.weld.WeldContainer.initialize(WeldContainer.java:72)
	... 10 more

```

The full log is attached.
[boot.log](https://github.com/piranhacloud/piranha/files/4640279/boot.log)

**Comment by manorrock** [comment]
Does it produce a similar log on Piranha Server?

**Comment by Thihup** [comment]
It goes a lot further, but I still can acess the Jenkins page.

I think the major exception it this one:

```
GRAVE: Failed to initialize Jenkins
hudson.util.HudsonFailedToLoad: java.lang.NoSuchMethodError: org/apache/commons/io/IOUtils.readLines(Ljava/io/InputStream;Ljava/nio/charset/Charset;)Ljava/util/List; (loaded from file:/home/thiago/Projects/piranha/server/target/piranha/lib/commons-io-2.2.jar by jdk.internal.loader.ClassLoaders$AppClassLoader@6a77dd04) called from class jenkins.security.stapler.StaplerDispatchValidator$ValidatorCache (loaded from <Unknown> by cloud.piranha.webapp.impl.DefaultWebApplicationClassLoader@f2665213).
	at hudson.WebAppMain$3.run(WebAppMain.java:276)
Caused by: java.lang.NoSuchMethodError: org/apache/commons/io/IOUtils.readLines(Ljava/io/InputStream;Ljava/nio/charset/Charset;)Ljava/util/List; (loaded from file:/home/thiago/Projects/piranha/server/target/piranha/lib/commons-io-2.2.jar by jdk.internal.loader.ClassLoaders$AppClassLoader@6a77dd04) called from class jenkins.security.stapler.StaplerDispatchValidator$ValidatorCache (loaded from <Unknown> by cloud.piranha.webapp.impl.DefaultWebApplicationClassLoader@f2665213).
	at jenkins.security.stapler.StaplerDispatchValidator$ValidatorCache.load(StaplerDispatchValidator.java:261)
	at jenkins.security.stapler.StaplerDispatchValidator$ValidatorCache.access$100(StaplerDispatchValidator.java:182)
	at jenkins.security.stapler.StaplerDispatchValidator.<init>(StaplerDispatchValidator.java:113)
	at jenkins.model.Jenkins.<init>(Jenkins.java:953)
	at hudson.model.Hudson.<init>(Hudson.java:85)
	at hudson.model.Hudson.<init>(Hudson.java:81)
	at hudson.WebAppMain$3.run(WebAppMain.java:262)
```

The log is attached
[boot.log](https://github.com/piranhacloud/piranha/files/4640368/boot.log)

**Comment by manorrock** [comment]
I have relocated the use of commons-io in the Piranha Apache File Upload module which should resolve the above stacktrace, see issue #749. Let me know how it goes.

**Comment by Thihup** [comment]
It still throwing the same exception :\
I could start the Jenkins a little more by excluding the current version of commons-io (2.2) and including the latest version (2.6).
I don't know if you would like to have another try or I can open a PR upgrading the version.

**Comment by Thihup** [comment]
Even with the shaded classes, it still includes both commons-io and commons-fileupload in Piranha Server build

**Comment by Thihup** [comment]
Just running the current version of Piranha Server with the Jenkins in webapps folder I still get the following error:

```
Exception in thread "Jenkins initialization thread" java.lang.NoSuchMethodError: org/apache/commons/io/IOUtils.readLines(Ljava/io/InputStream;Ljava/nio/charset/Charset;)Ljava/util/List; (loaded from file:/home/thiago/Projects/my-piranha/server/target/piranha/lib/commons-io-2.2.jar by jdk.internal.loader.ClassLoaders$AppClassLoader@205874c5) called from class jenkins.security.ClassFilterImpl (loaded from <Unknown> by cloud.piranha.webapp.impl.DefaultWebApplicationClassLoader@925c9532).
	at jenkins.security.ClassFilterImpl.<clinit>(ClassFilterImpl.java:120)
	at jenkins.model.Jenkins.cleanUp(Jenkins.java:3465)
	at hudson.WebAppMain$3.run(WebAppMain.java:283)
```

However, if I remove both commons-fileupload-1.4.jar and commons-io-2.2.jar from lib folder, the Jenkins initialization does proceed, but it fails with the following exception:

```
java.io.IOException: java.lang.UnsupportedOperationException: Refusing to marshal hudson.model.Queue$State for security reasons; see https://jenkins.io/redirect/class-filter/
	at hudson.XmlFile.write(XmlFile.java:202)
	at hudson.model.Queue.save(Queue.java:491)
	at jenkins.model.Jenkins._cleanUpPersistQueue(Jenkins.java:3682)
	at jenkins.model.Jenkins.cleanUp(Jenkins.java:3433)
	at hudson.WebAppMain$3.run(WebAppMain.java:283)
Caused by: java.lang.UnsupportedOperationException: Refusing to marshal hudson.model.Queue$State for security reasons; see https://jenkins.io/redirect/class-filter/
	at hudson.util.XStream2$BlacklistedTypesConverter.marshal(XStream2.java:541)
	at com.thoughtworks.xstream.core.AbstractReferenceMarshaller.convert(AbstractReferenceMarshaller.java:69)
	at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:58)
	at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:43)
	at com.thoughtworks.xstream.core.TreeMarshaller.start(TreeMarshaller.java:82)
	at com.thoughtworks.xstream.core.AbstractTreeMarshallingStrategy.marshal(AbstractTreeMarshallingStrategy.java:37)
	at com.thoughtworks.xstream.XStream.marshal(XStream.java:1026)
	at com.thoughtworks.xstream.XStream.marshal(XStream.java:1015)
	at com.thoughtworks.xstream.XStream.toXML(XStream.java:988)
	at hudson.XmlFile.write(XmlFile.java:195)
	... 4 more
```

I don't know why it happens. If I add hudson.model.Queue$State to hudson.remoting.ClassFilter property, it will fail with another and another. But after a while, I could bypass with the following classes:

```
-Dhudson.remoting.ClassFilter=hudson.model.Queue$State,hudson.model.UserIdMapper,hudson.model.User,jenkins.security.ApiTokenProperty,jenkins.security.apitoken.ApiTokenStore,hudson.search.UserSearchProperty,hudson.model.MyViewsProperty,hudson.model.AllView,hudson.model.View$PropertyList,hudson.model.PaneStatusProperties,hudson.util.PersistedList,jenkins.security.seed.UserSeedProperty,hudson.model.TimeZoneProperty,hudson.security.HudsonPrivateSecurityRealm$Details,hudson.model.Hudson,hudson.security.FullControlOnceLoggedInAuthorizationStrategy,hudson.security.HudsonPrivateSecurityRealm,jenkins.model.ProjectNamingStrategy$DefaultProjectNamingStrategy,hudson.views.DefaultViewsTabBar,hudson.views.DefaultMyViewsTabBar,hudson.model.Hudson$CloudList,hudson.security.csrf.DefaultCrumbIssuer,hudson.util.DescribableList,hudson.node_monitors.ArchitectureMonitor,jenkins.telemetry.Correlator,hudson.model.UpdateSite,hudson.node_monitors.ClockMonitor,hudson.node_monitors.SwapSpaceMonitor,hudson.node_monitors.DiskSpaceMonitor,hudson.node_monitors.TemporarySpaceMonitor,hudson.node_monitors.ResponseTimeMonitor,hudson.security.AuthorizationStrategy$Unsecured,hudson.model.View$PropertyList,jenkins.security.LastGrantedAuthoritiesProperty,hudson.security.SecurityRealm$None
```

Then we get the success message in the console: "Jenkins is fully up and running" :)

After this, at http://localhost:8080/jenkins/ we are asked to unlock Jenkins (normal procedure), but the page wasn't able to load any JS and CSS. For some reason, all resources have the Content-Type: text/html in the response.

**Comment by manorrock** [comment]
Please have another try, I updated the shading so it should no work better from scratch

**Comment by Thihup** [comment]
Unfortunately I still get the same exception at the start.
The Jenkins war includes in WEB-INF/lib the commons-io-2.6.jar and commons-fileupload-1.3.1.jar.

The main flaw is that commons-io-2.2.jar and  commons-fileupload-1.4.jar is already included in the MANIFEST.MF of the piranha-server.jar. For this reason removing them of lib folder makes the application start correctly.

Now that both jars are shaded, shoudn't they be removed from lib folder?

**Comment by manorrock** [comment]
Yes they should. This time they should be for sure ;)

**Comment by Thihup** [comment]
Alright, sorry for the late response. This time it is OK. Thanks.

About the  hudson.remoting.ClassFilter, I could see that looks like it is a problem with `class.getProtectionDomain().getCodeSource()`.
In Tomcat, the code source contains the attribute "location", but in Piranha Server it is null. I still trying to figure it out why.

**Comment by manorrock** [comment]
Ah good find!

**Comment by manorrock** [comment]
@Thihup So I can go ahead and close this now?

**Comment by Thihup** [comment]
Not yet. I couldn't use the Jenkins properly. Actually I wasn't able to pass the installation process.

**Comment by manorrock** [comment]
OK so what other issues are you seeing?

**Comment by Thihup** [comment]
Currently, the issues I found out are these: 

- The Jenkins doesn't load the files correctly (all static files like CSS and JS) because it creates a cache from ServletContext.getResourcePaths().
However, in our current implementation, it only returns null, not allowing Jenkins to read the files correctly. https://github.com/piranhacloud/piranha/issues/769

 - If the request contains the Cookie header that contains a name that doesn't have a value it throws ArrayIndexOutOfBoundsException.(e.g: Cookie: a=b;INVALID=;c=d) 

- If the response tries to write a cookie that doesn't have a value, it throws NPE.

- The encoding of the response isn't right. I will dig to see whether it's a Piranha's issue or it's from Jenkins.

**Comment by manorrock** [comment]
Feel free to add the SVG mime-type to the DefaultMimeTypeManager

**Comment by Thihup** [comment]
I think the main issue now is only the #769 
For now, it is possible to use the Jenkins with the following property: 
`-Dorg.kohsuke.stapler.Stapler.noResourcePathCache=true`

I am closing this issue since with the current status of Piranha Server it is already possible to use Jenkins.
