### ISSUE TITLE
Piranha Micro don't load classes from WEB-INF/lib

### ISSUE THREAD

**Issue by Thihup** [piranhacloud/piranha#823]
The Piranha Micro is not currently reading the classes from WEB-INF/lib. An example is we can't deploy a war that doesn't contain any WEB-INF/classes.

As I can tell, there are two main reasons for this is happening:
1. MicroOuterDeployer does not add libs from WEB-INF/lib as resources, only classes from WEB-INF/classes and a Jandex file.
2. PiranhaBeanArchiveHandler only looks for WEB-INF/classes. If we add the jars as resources, it still won't find and file because the protocol for each file is "shrinkwrap://". This way, as the libs weren't added to the indexer, so the Weld thinks there isn't any deployment, causing it to fail.

I was trying stuff around and we can make a Jandex file that scans all jars. The main issue is that it some deployments will probably fail if it shoudn't use CDI injection.
[Here](https://github.com/Thihup/piranha/commit/67788756cd0fbfd060130300f76e8b065ec1dbc1) is my quick and dirty attempt to fix, but maybe I missed something.

**Comment by arjantijms** [comment]
Thanks @Thihup!

I implemented things a bit differently, as the jar file entries (which are a ZipFileEntryAsset) actually need to be imported.

The javadoc for getAsType says: 

```java
    /**
     * Get a nested {@link Archive} as a specific type.<br/>
     * <br/>
     *
     * The found Archives must have been added as a Archive, no import is performed.
     *
     * @param <X>
     * @param type
     *            The Type to return the Archive as
     * @param path
     *            The location of the Archive
     * @return The found Archive as given type or null if none found at given path
     * @throws IllegalArgumentException
     *             if found {@link Asset} is not pointing to a {@link Archive}
     * @see Archive#getAsType(Class, ArchivePath)
     * @see Archive#add(Archive, ArchivePath, Class)
     * @see Archive#add(Archive, String, Class)
     */
    <X extends Archive<X>> X getAsType(Class<X> type, String path);
```

So just saying 

```java
applicationArchive.getAsType(JavaArchive.class, "/WEB-INF/lib" + x)
```

Only works, I think, if those entries/assets were added as archive, but they are low-level zip entries in this case.

**Comment by Thihup** [comment]
Thanks for the explanation! 
However we still have a problem: 
```
WARN: WELD-ENV-000028: Weld initialization skipped - no bean archive found
jun. 04, 2020 2:44:43 PM cloud.piranha.webapp.impl.DefaultWebApplication initializeInitializers
WARN: Initializer cloud.piranha.security.jakarta.JakartaSecurityAllInitializer failing onStartup
java.lang.IllegalStateException: Singleton not set for cloud.piranha.webapp.impl.DefaultWebApplication@a654cb81 => []
```

The main reason is that Weld cannot read those jars added here because it doesn't support Shrinkwrap files by default. We currently have the PiranhaBeanArchiveHandler, but it only handles the WEB-INF/classes because of the Jandex. But for those jars, the Weld doesn't anything about it the thinks there is no deployment. 

I'm still figuring it out how to read the jars from the PiranhaBeanArchiveHandler, because we only have the file like "shrinkwrap://some.jar".

If you could take a look at this I'd appreciate

**Comment by manorrock** [comment]
@Thihup Have another look ;)
